# Generated by Django 2.2.24 on 2021-07-16 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='タイトル')),
            ],
        ),
        migrations.CreateModel(
            name='Music_by_feeling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='タイトル')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='日付')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='music_by_feeling.Category')),
            ],
        ),
    ]
