# Generated by Django 2.1.5 on 2022-09-05 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_by_feeling', '0002_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feeling_1', models.CharField(default='5', max_length=10)),
                ('feeling_2', models.CharField(default='5', max_length=10)),
                ('artist', models.CharField(default='5', max_length=20)),
                ('genre', models.CharField(choices=[('1', 'J-POP'), ('2', 'K-POP'), ('3', 'アニメ'), ('4', 'クラシック'), ('5', 'ロック')], default='', max_length=5, verbose_name='ジャンル')),
                ('era', models.CharField(choices=[('1', '1980'), ('2', '1990'), ('3', '2000'), ('4', '2010'), ('5', '2020')], default='', max_length=5, verbose_name='年代')),
                ('famous', models.BooleanField(default=False)),
            ],
        ),
    ]
