# Generated by Django 2.1.5 on 2022-09-24 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_by_feeling', '0004_favoritemusiclist_music_by_feelinglist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritemusiclist',
            name='external_urls',
            field=models.CharField(max_length=50, null=True, verbose_name='外部URL'),
        ),
        migrations.AlterField(
            model_name='favoritemusiclist',
            name='genres',
            field=models.CharField(max_length=50, null=True, verbose_name='ジャンル'),
        ),
        migrations.AlterField(
            model_name='favoritemusiclist',
            name='images',
            field=models.CharField(max_length=50, null=True, verbose_name='イメージ'),
        ),
        migrations.AlterField(
            model_name='favoritemusiclist',
            name='result1',
            field=models.CharField(max_length=50, null=True, verbose_name='結果1'),
        ),
        migrations.AlterField(
            model_name='favoritemusiclist',
            name='uri',
            field=models.CharField(max_length=50, null=True, verbose_name='URI'),
        ),
        migrations.AlterField(
            model_name='music',
            name='artist',
            field=models.CharField(blank=True, default='5', max_length=20),
        ),
        migrations.AlterField(
            model_name='music',
            name='era',
            field=models.CharField(blank=True, choices=[('1', '1980'), ('2', '1990'), ('3', '2000'), ('4', '2010'), ('5', '2020')], default='', max_length=5, verbose_name='年代'),
        ),
        migrations.AlterField(
            model_name='music',
            name='famous',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='music',
            name='genre',
            field=models.CharField(blank=True, choices=[('1', 'J-POP'), ('2', 'K-POP'), ('3', 'アニメ'), ('4', 'クラシック'), ('5', 'ロック')], default='', max_length=5, verbose_name='ジャンル'),
        ),
        migrations.AlterField(
            model_name='music_by_feelinglist',
            name='external_urls',
            field=models.CharField(max_length=50, null=True, verbose_name='外部URL'),
        ),
        migrations.AlterField(
            model_name='music_by_feelinglist',
            name='genres',
            field=models.CharField(max_length=50, null=True, verbose_name='ジャンル'),
        ),
        migrations.AlterField(
            model_name='music_by_feelinglist',
            name='images',
            field=models.CharField(max_length=50, null=True, verbose_name='イメージ'),
        ),
        migrations.AlterField(
            model_name='music_by_feelinglist',
            name='result1',
            field=models.CharField(max_length=50, null=True, verbose_name='結果1'),
        ),
        migrations.AlterField(
            model_name='music_by_feelinglist',
            name='uri',
            field=models.CharField(max_length=50, null=True, verbose_name='URI'),
        ),
    ]
