# Generated by Django 2.2.28 on 2022-10-10 23:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music_by_feeling', '0005_auto_20220924_1138'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feeling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotify_activeness', models.FloatField()),
                ('spotify_positiveness', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.SmallIntegerField()),
                ('sex', models.CharField(max_length=10)),
                ('feeling', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeling', to='music_by_feeling.Feeling')),
                ('history_music', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_music', to='music_by_feeling.Music_by_feelingList')),
                ('like_music', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_music', to='music_by_feeling.Music_by_feelingList')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
