# Generated by Django 2.1.5 on 2022-10-09 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_by_feeling', '0005_auto_20220924_1138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music_by_feeling',
            name='category',
        ),
        migrations.RemoveField(
            model_name='music_by_feeling',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='music_by_feeling',
            name='title',
        ),
        migrations.AddField(
            model_name='music_by_feeling',
            name='acousticness',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='アコースティック感'),
        ),
        migrations.AddField(
            model_name='music_by_feeling',
            name='artist',
            field=models.CharField(max_length=50, null=True, verbose_name='アーティストタイトル'),
        ),
        migrations.AddField(
            model_name='music_by_feeling',
            name='danceability',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='踊りやすさ'),
        ),
        migrations.AddField(
            model_name='music_by_feeling',
            name='energy',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='エネルギッシュ'),
        ),
        migrations.AddField(
            model_name='music_by_feeling',
            name='instrumentalness',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='ボーカル無し度'),
        ),
        migrations.AddField(
            model_name='music_by_feeling',
            name='key',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='曲の高さ'),
        ),
        migrations.AddField(
            model_name='music_by_feeling',
            name='liveness',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='ライブ感'),
        ),
        migrations.AddField(
            model_name='music_by_feeling',
            name='loudness',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='音圧'),
        ),
        migrations.AddField(
            model_name='music_by_feeling',
            name='mode',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='スケール'),
        ),
        migrations.AddField(
            model_name='music_by_feeling',
            name='speechiness',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='話し言葉度'),
        ),
        migrations.AddField(
            model_name='music_by_feeling',
            name='tempo',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='テンポ'),
        ),
        migrations.AddField(
            model_name='music_by_feeling',
            name='tracks',
            field=models.CharField(max_length=50, null=True, verbose_name='トラックタイトル'),
        ),
        migrations.AddField(
            model_name='music_by_feeling',
            name='type',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='タイプ'),
        ),
        migrations.AddField(
            model_name='music_by_feeling',
            name='url',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='music_by_feeling',
            name='valence',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='ポジティブ'),
        ),
    ]
