# Generated by Django 2.2.28 on 2022-10-11 05:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music_by_feeling', '0006_account_feeling'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='feeling',
        ),
        migrations.RemoveField(
            model_name='account',
            name='history_music',
        ),
        migrations.RemoveField(
            model_name='account',
            name='like_music',
        ),
        migrations.AddField(
            model_name='favoritemusiclist',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='music',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='music_by_feelinglist',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='sex',
            field=models.CharField(blank=True, choices=[('1', 'male'), ('2', 'female'), ('3', 'other')], default='', max_length=3),
        ),
        migrations.DeleteModel(
            name='Feeling',
        ),
    ]
