# Generated by Django 2.1.5 on 2022-10-10 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_by_feeling', '0006_auto_20221009_2345'),
    ]

    operations = [
        migrations.RenameField(
            model_name='music_by_feeling',
            old_name='tracks',
            new_name='title',
        ),
    ]
