# Generated by Django 2.1.5 on 2022-10-10 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music_by_feeling', '0007_auto_20221010_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='music_by_feeling',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='music_by_feeling.Category'),
        ),
        migrations.AddField(
            model_name='music_by_feeling',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='日付'),
        ),
    ]
