# Generated by Django 2.2.28 on 2022-10-25 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_by_feeling', '0008_auto_20221025_1216'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllMusic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracks', models.CharField(max_length=50, null=True, verbose_name='トラックタイトル')),
                ('artist', models.CharField(max_length=50, null=True, verbose_name='アーティストタイトル')),
                ('danceability', models.FloatField(blank=True, default=0.0, null=True, verbose_name='踊りやすさ')),
                ('energy', models.FloatField(blank=True, default=0.0, null=True, verbose_name='エネルギッシュ')),
                ('key', models.FloatField(blank=True, default=0.0, null=True, verbose_name='曲の高さ')),
                ('loudness', models.FloatField(blank=True, default=0.0, null=True, verbose_name='音圧')),
                ('mode', models.FloatField(blank=True, default=0.0, null=True, verbose_name='スケール')),
                ('speechiness', models.FloatField(blank=True, default=0.0, null=True, verbose_name='話し言葉度')),
                ('acousticness', models.FloatField(blank=True, default=0.0, null=True, verbose_name='アコースティック感')),
                ('instrumentalness', models.FloatField(blank=True, default=0.0, null=True, verbose_name='ボーカル無し度')),
                ('liveness', models.FloatField(blank=True, default=0.0, null=True, verbose_name='ライブ感')),
                ('valence', models.FloatField(blank=True, default=0.0, null=True, verbose_name='ポジティブ')),
                ('tempo', models.FloatField(blank=True, default=0.0, null=True, verbose_name='テンポ')),
                ('type', models.CharField(max_length=50, null=True, verbose_name='タイプ')),
                ('url', models.CharField(max_length=100, null=True, verbose_name='URL')),
                ('track_id', models.CharField(max_length=100, null=True, verbose_name='track_id')),
                ('uri', models.CharField(max_length=100, null=True, verbose_name='URI')),
                ('track_href', models.CharField(max_length=100, null=True, verbose_name='曲の詳細情報にアクセスするAPIリンク')),
                ('analysis_url', models.CharField(max_length=100, null=True, verbose_name='曲のオーディオ分析にアクセスするAPIリンク')),
                ('duration_ms', models.FloatField(blank=True, default=0.0, null=True, verbose_name='曲の長さ')),
                ('time_signature', models.FloatField(blank=True, default=0.0, null=True, verbose_name='拍数')),
                ('artist_url', models.CharField(max_length=100, null=True, verbose_name='アーティストURL')),
                ('genres', models.CharField(max_length=100, null=True, verbose_name='ジャンル')),
                ('popularity', models.IntegerField(blank=True, default=0, null=True, verbose_name='人気度')),
                ('track_url', models.CharField(max_length=100, null=True, verbose_name='track_url')),
                ('created_year', models.IntegerField(blank=True, default=0, null=True, verbose_name='年')),
                ('rank', models.IntegerField(blank=True, default=0, null=True, verbose_name='順位')),
            ],
        ),
        migrations.RemoveField(
            model_name='favoritemusiclist',
            name='external_urls',
        ),
        migrations.RemoveField(
            model_name='favoritemusiclist',
            name='images',
        ),
        migrations.RemoveField(
            model_name='favoritemusiclist',
            name='name',
        ),
        migrations.RemoveField(
            model_name='favoritemusiclist',
            name='result1',
        ),
        migrations.RemoveField(
            model_name='music_by_feelinglist',
            name='external_urls',
        ),
        migrations.RemoveField(
            model_name='music_by_feelinglist',
            name='images',
        ),
        migrations.RemoveField(
            model_name='music_by_feelinglist',
            name='name',
        ),
        migrations.RemoveField(
            model_name='music_by_feelinglist',
            name='result1',
        ),
        migrations.AddField(
            model_name='favoritemusiclist',
            name='acousticness',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='アコースティック感'),
        ),
        migrations.AddField(
            model_name='favoritemusiclist',
            name='analysis_url',
            field=models.CharField(max_length=100, null=True, verbose_name='曲のオーディオ分析にアクセスするAPIリンク'),
        ),
        migrations.AddField(
            model_name='favoritemusiclist',
            name='artist',
            field=models.CharField(max_length=50, null=True, verbose_name='アーティストタイトル'),
        ),
        migrations.AddField(
            model_name='favoritemusiclist',
            name='artist_url',
            field=models.CharField(max_length=100, null=True, verbose_name='アーティストURL'),
        ),
        migrations.AddField(
            model_name='favoritemusiclist',
            name='created_year',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='年'),
        ),
        migrations.AddField(
            model_name='favoritemusiclist',
            name='danceability',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='踊りやすさ'),
        ),
        migrations.AddField(
            model_name='favoritemusiclist',
            name='duration_ms',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='曲の長さ'),
        ),
        migrations.AddField(
            model_name='favoritemusiclist',
            name='energy',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='エネルギッシュ'),
        ),
        migrations.AddField(
            model_name='favoritemusiclist',
            name='instrumentalness',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='ボーカル無し度'),
        ),
        migrations.AddField(
            model_name='favoritemusiclist',
            name='key',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='曲の高さ'),
        ),
        migrations.AddField(
            model_name='favoritemusiclist',
            name='liveness',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='ライブ感'),
        ),
        migrations.AddField(
            model_name='favoritemusiclist',
            name='loudness',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='音圧'),
        ),
        migrations.AddField(
            model_name='favoritemusiclist',
            name='mode',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='スケール'),
        ),
        migrations.AddField(
            model_name='favoritemusiclist',
            name='order',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='通し番号'),
        ),
        migrations.AddField(
            model_name='favoritemusiclist',
            name='rank',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='順位'),
        ),
        migrations.AddField(
            model_name='favoritemusiclist',
            name='speechiness',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='話し言葉度'),
        ),
        migrations.AddField(
            model_name='favoritemusiclist',
            name='tempo',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='テンポ'),
        ),
        migrations.AddField(
            model_name='favoritemusiclist',
            name='time_signature',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='拍数'),
        ),
        migrations.AddField(
            model_name='favoritemusiclist',
            name='track_href',
            field=models.CharField(max_length=100, null=True, verbose_name='曲の詳細情報にアクセスするAPIリンク'),
        ),
        migrations.AddField(
            model_name='favoritemusiclist',
            name='track_id',
            field=models.CharField(max_length=100, null=True, verbose_name='track_id'),
        ),
        migrations.AddField(
            model_name='favoritemusiclist',
            name='track_url',
            field=models.CharField(max_length=100, null=True, verbose_name='track_url'),
        ),
        migrations.AddField(
            model_name='favoritemusiclist',
            name='tracks',
            field=models.CharField(max_length=50, null=True, verbose_name='トラックタイトル'),
        ),
        migrations.AddField(
            model_name='favoritemusiclist',
            name='type',
            field=models.CharField(max_length=50, null=True, verbose_name='タイプ'),
        ),
        migrations.AddField(
            model_name='favoritemusiclist',
            name='url',
            field=models.CharField(max_length=100, null=True, verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='favoritemusiclist',
            name='valence',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='ポジティブ'),
        ),
        migrations.AddField(
            model_name='music_by_feelinglist',
            name='acousticness',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='アコースティック感'),
        ),
        migrations.AddField(
            model_name='music_by_feelinglist',
            name='analysis_url',
            field=models.CharField(max_length=100, null=True, verbose_name='曲のオーディオ分析にアクセスするAPIリンク'),
        ),
        migrations.AddField(
            model_name='music_by_feelinglist',
            name='artist',
            field=models.CharField(max_length=50, null=True, verbose_name='アーティストタイトル'),
        ),
        migrations.AddField(
            model_name='music_by_feelinglist',
            name='artist_url',
            field=models.CharField(max_length=100, null=True, verbose_name='アーティストURL'),
        ),
        migrations.AddField(
            model_name='music_by_feelinglist',
            name='created_year',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='年'),
        ),
        migrations.AddField(
            model_name='music_by_feelinglist',
            name='danceability',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='踊りやすさ'),
        ),
        migrations.AddField(
            model_name='music_by_feelinglist',
            name='duration_ms',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='曲の長さ'),
        ),
        migrations.AddField(
            model_name='music_by_feelinglist',
            name='energy',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='エネルギッシュ'),
        ),
        migrations.AddField(
            model_name='music_by_feelinglist',
            name='instrumentalness',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='ボーカル無し度'),
        ),
        migrations.AddField(
            model_name='music_by_feelinglist',
            name='key',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='曲の高さ'),
        ),
        migrations.AddField(
            model_name='music_by_feelinglist',
            name='liveness',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='ライブ感'),
        ),
        migrations.AddField(
            model_name='music_by_feelinglist',
            name='loudness',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='音圧'),
        ),
        migrations.AddField(
            model_name='music_by_feelinglist',
            name='mode',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='スケール'),
        ),
        migrations.AddField(
            model_name='music_by_feelinglist',
            name='order',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='通し番号'),
        ),
        migrations.AddField(
            model_name='music_by_feelinglist',
            name='rank',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='順位'),
        ),
        migrations.AddField(
            model_name='music_by_feelinglist',
            name='speechiness',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='話し言葉度'),
        ),
        migrations.AddField(
            model_name='music_by_feelinglist',
            name='tempo',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='テンポ'),
        ),
        migrations.AddField(
            model_name='music_by_feelinglist',
            name='time_signature',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='拍数'),
        ),
        migrations.AddField(
            model_name='music_by_feelinglist',
            name='track_href',
            field=models.CharField(max_length=100, null=True, verbose_name='曲の詳細情報にアクセスするAPIリンク'),
        ),
        migrations.AddField(
            model_name='music_by_feelinglist',
            name='track_id',
            field=models.CharField(max_length=100, null=True, verbose_name='track_id'),
        ),
        migrations.AddField(
            model_name='music_by_feelinglist',
            name='track_url',
            field=models.CharField(max_length=100, null=True, verbose_name='track_url'),
        ),
        migrations.AddField(
            model_name='music_by_feelinglist',
            name='tracks',
            field=models.CharField(max_length=50, null=True, verbose_name='トラックタイトル'),
        ),
        migrations.AddField(
            model_name='music_by_feelinglist',
            name='type',
            field=models.CharField(max_length=50, null=True, verbose_name='タイプ'),
        ),
        migrations.AddField(
            model_name='music_by_feelinglist',
            name='url',
            field=models.CharField(max_length=100, null=True, verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='music_by_feelinglist',
            name='valence',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='ポジティブ'),
        ),
        migrations.AlterField(
            model_name='favoritemusiclist',
            name='genres',
            field=models.CharField(max_length=100, null=True, verbose_name='ジャンル'),
        ),
        migrations.AlterField(
            model_name='favoritemusiclist',
            name='popularity',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='人気度'),
        ),
        migrations.AlterField(
            model_name='favoritemusiclist',
            name='uri',
            field=models.CharField(max_length=100, null=True, verbose_name='URI'),
        ),
        migrations.AlterField(
            model_name='music_by_feelinglist',
            name='genres',
            field=models.CharField(max_length=100, null=True, verbose_name='ジャンル'),
        ),
        migrations.AlterField(
            model_name='music_by_feelinglist',
            name='popularity',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='人気度'),
        ),
        migrations.AlterField(
            model_name='music_by_feelinglist',
            name='uri',
            field=models.CharField(max_length=100, null=True, verbose_name='URI'),
        ),
    ]
