# Generated by Django 2.1.5 on 2022-10-10 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_by_feeling', '0009_auto_20221010_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allmusics',
            name='url',
            field=models.CharField(max_length=50, null=True, verbose_name='URL'),
        ),
    ]
