# Generated by Django 2.1.5 on 2022-10-10 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_by_feeling', '0010_auto_20221010_1946'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AllMusics',
            new_name='AllMusic',
        ),
    ]
