# Generated by Django 2.1.5 on 2022-10-10 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_by_feeling', '0012_auto_20221010_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allmusic',
            name='danceability',
            field=models.FloatField(blank=True, default=1.0, null=True, verbose_name='踊りやすさ'),
        ),
        migrations.AlterField(
            model_name='allmusic',
            name='energy',
            field=models.FloatField(blank=True, default=1.0, null=True, verbose_name='エネルギッシュ'),
        ),
        migrations.AlterField(
            model_name='allmusic',
            name='key',
            field=models.FloatField(blank=True, default=1.0, null=True, verbose_name='曲の高さ'),
        ),
    ]
