# Generated by Django 2.1.5 on 2022-10-10 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_by_feeling', '0013_auto_20221010_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allmusic',
            name='type',
            field=models.CharField(max_length=50, null=True, verbose_name='タイプ'),
        ),
    ]
