# Generated by Django 2.1.5 on 2022-10-10 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_by_feeling', '0014_auto_20221010_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='allmusic',
            name='analysis_url',
            field=models.CharField(max_length=100, null=True, verbose_name='曲のオーディオ分析にアクセスするAPIリンク'),
        ),
        migrations.AddField(
            model_name='allmusic',
            name='duration_ms',
            field=models.FloatField(blank=True, default=1.0, null=True, verbose_name='曲の長さ'),
        ),
        migrations.AddField(
            model_name='allmusic',
            name='time_signature',
            field=models.FloatField(blank=True, default=1.0, null=True, verbose_name='拍数'),
        ),
        migrations.AddField(
            model_name='allmusic',
            name='track_href',
            field=models.CharField(max_length=100, null=True, verbose_name='曲の詳細情報にアクセスするAPIリンク'),
        ),
        migrations.AddField(
            model_name='allmusic',
            name='track_id',
            field=models.CharField(max_length=100, null=True, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='allmusic',
            name='uri',
            field=models.CharField(max_length=100, null=True, verbose_name='URI'),
        ),
    ]
