# Generated by Django 2.1.5 on 2022-10-10 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_by_feeling', '0015_auto_20221010_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='allmusic',
            name='genres',
            field=models.CharField(max_length=100, null=True, verbose_name='ジャンル'),
        ),
    ]
