# Generated by Django 2.1.5 on 2022-10-10 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_by_feeling', '0017_allmusic_artist_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='allmusic',
            name='popularity',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='人気度'),
        ),
    ]
