# Generated by Django 2.1.5 on 2022-10-13 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_by_feeling', '0019_auto_20221013_1857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music_by_feelinglist',
            name='acousticness',
        ),
        migrations.RemoveField(
            model_name='music_by_feelinglist',
            name='analysis_url',
        ),
        migrations.RemoveField(
            model_name='music_by_feelinglist',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='music_by_feelinglist',
            name='artist_url',
        ),
        migrations.RemoveField(
            model_name='music_by_feelinglist',
            name='danceability',
        ),
        migrations.RemoveField(
            model_name='music_by_feelinglist',
            name='duration_ms',
        ),
        migrations.RemoveField(
            model_name='music_by_feelinglist',
            name='energy',
        ),
        migrations.RemoveField(
            model_name='music_by_feelinglist',
            name='genres',
        ),
        migrations.RemoveField(
            model_name='music_by_feelinglist',
            name='instrumentalness',
        ),
        migrations.RemoveField(
            model_name='music_by_feelinglist',
            name='key',
        ),
        migrations.RemoveField(
            model_name='music_by_feelinglist',
            name='liveness',
        ),
        migrations.RemoveField(
            model_name='music_by_feelinglist',
            name='loudness',
        ),
        migrations.RemoveField(
            model_name='music_by_feelinglist',
            name='mode',
        ),
        migrations.RemoveField(
            model_name='music_by_feelinglist',
            name='popularity',
        ),
        migrations.RemoveField(
            model_name='music_by_feelinglist',
            name='speechiness',
        ),
        migrations.RemoveField(
            model_name='music_by_feelinglist',
            name='tempo',
        ),
        migrations.RemoveField(
            model_name='music_by_feelinglist',
            name='time_signature',
        ),
        migrations.RemoveField(
            model_name='music_by_feelinglist',
            name='track_href',
        ),
        migrations.RemoveField(
            model_name='music_by_feelinglist',
            name='track_id',
        ),
        migrations.RemoveField(
            model_name='music_by_feelinglist',
            name='type',
        ),
        migrations.RemoveField(
            model_name='music_by_feelinglist',
            name='uri',
        ),
        migrations.RemoveField(
            model_name='music_by_feelinglist',
            name='url',
        ),
        migrations.RemoveField(
            model_name='music_by_feelinglist',
            name='valence',
        ),
    ]
