# Generated by Django 2.1.5 on 2022-10-14 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_by_feeling', '0021_auto_20221013_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music_by_feelinglist',
            name='track_id',
            field=models.CharField(max_length=100, null=True, verbose_name='track_id'),
        ),
    ]
