# Generated by Django 2.1.5 on 2022-10-14 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_by_feeling', '0022_auto_20221014_2001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoritemusiclist',
            name='external_urls',
        ),
        migrations.RemoveField(
            model_name='favoritemusiclist',
            name='images',
        ),
        migrations.RemoveField(
            model_name='favoritemusiclist',
            name='name',
        ),
        migrations.RemoveField(
            model_name='favoritemusiclist',
            name='result1',
        ),
        migrations.AddField(
            model_name='favoritemusiclist',
            name='acousticness',
            field=models.FloatField(blank=True, default=1.0, null=True, verbose_name='アコースティック感'),
        ),
        migrations.AddField(
            model_name='favoritemusiclist',
            name='analysis_url',
            field=models.CharField(max_length=100, null=True, verbose_name='曲のオーディオ分析にアクセスするAPIリンク'),
        ),
        migrations.AddField(
            model_name='favoritemusiclist',
            name='artist',
            field=models.CharField(max_length=50, null=True, verbose_name='アーティストタイトル'),
        ),
        migrations.AddField(
            model_name='favoritemusiclist',
            name='artist_url',
            field=models.CharField(max_length=100, null=True, verbose_name='アーティストURL'),
        ),
        migrations.AddField(
            model_name='favoritemusiclist',
            name='danceability',
            field=models.FloatField(blank=True, default=1.0, null=True, verbose_name='踊りやすさ'),
        ),
        migrations.AddField(
            model_name='favoritemusiclist',
            name='duration_ms',
            field=models.FloatField(blank=True, default=1.0, null=True, verbose_name='曲の長さ'),
        ),
        migrations.AddField(
            model_name='favoritemusiclist',
            name='energy',
            field=models.FloatField(blank=True, default=1.0, null=True, verbose_name='エネルギッシュ'),
        ),
        migrations.AddField(
            model_name='favoritemusiclist',
            name='instrumentalness',
            field=models.FloatField(blank=True, default=1.0, null=True, verbose_name='ボーカル無し度'),
        ),
        migrations.AddField(
            model_name='favoritemusiclist',
            name='key',
            field=models.FloatField(blank=True, default=1.0, null=True, verbose_name='曲の高さ'),
        ),
        migrations.AddField(
            model_name='favoritemusiclist',
            name='liveness',
            field=models.FloatField(blank=True, default=1.0, null=True, verbose_name='ライブ感'),
        ),
        migrations.AddField(
            model_name='favoritemusiclist',
            name='loudness',
            field=models.FloatField(blank=True, default=1.0, null=True, verbose_name='音圧'),
        ),
        migrations.AddField(
            model_name='favoritemusiclist',
            name='mode',
            field=models.FloatField(blank=True, default=1.0, null=True, verbose_name='スケール'),
        ),
        migrations.AddField(
            model_name='favoritemusiclist',
            name='speechiness',
            field=models.FloatField(blank=True, default=1.0, null=True, verbose_name='話し言葉度'),
        ),
        migrations.AddField(
            model_name='favoritemusiclist',
            name='tempo',
            field=models.FloatField(blank=True, default=1.0, null=True, verbose_name='テンポ'),
        ),
        migrations.AddField(
            model_name='favoritemusiclist',
            name='time_signature',
            field=models.FloatField(blank=True, default=1.0, null=True, verbose_name='拍数'),
        ),
        migrations.AddField(
            model_name='favoritemusiclist',
            name='track_href',
            field=models.CharField(max_length=100, null=True, verbose_name='曲の詳細情報にアクセスするAPIリンク'),
        ),
        migrations.AddField(
            model_name='favoritemusiclist',
            name='track_id',
            field=models.CharField(max_length=100, null=True, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='favoritemusiclist',
            name='tracks',
            field=models.CharField(max_length=50, null=True, verbose_name='トラックタイトル'),
        ),
        migrations.AddField(
            model_name='favoritemusiclist',
            name='type',
            field=models.CharField(max_length=50, null=True, verbose_name='タイプ'),
        ),
        migrations.AddField(
            model_name='favoritemusiclist',
            name='url',
            field=models.CharField(max_length=100, null=True, verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='favoritemusiclist',
            name='valence',
            field=models.FloatField(blank=True, default=1.0, null=True, verbose_name='ポジティブ'),
        ),
        migrations.AlterField(
            model_name='favoritemusiclist',
            name='genres',
            field=models.CharField(max_length=100, null=True, verbose_name='ジャンル'),
        ),
        migrations.AlterField(
            model_name='favoritemusiclist',
            name='uri',
            field=models.CharField(max_length=100, null=True, verbose_name='URI'),
        ),
    ]
