# Generated by Django 2.1.5 on 2022-10-18 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_by_feeling', '0026_auto_20221015_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allmusic',
            name='danceability',
            field=models.IntegerField(blank=True, default=1.0, null=True, verbose_name='踊りやすさ'),
        ),
    ]
