# Generated by Django 2.1.5 on 2022-10-18 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_by_feeling', '0027_auto_20221018_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allmusic',
            name='danceability',
            field=models.FloatField(blank=True, default=1.0, null=True, verbose_name='踊りやすさ'),
        ),
        migrations.AlterField(
            model_name='allmusic',
            name='popularity',
            field=models.FloatField(blank=True, default=1, null=True, verbose_name='人気度'),
        ),
    ]
