# Generated by Django 2.1.5 on 2022-10-18 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_by_feeling', '0028_auto_20221018_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allmusic',
            name='popularity',
            field=models.CharField(max_length=100, null=True, verbose_name='人気度'),
        ),
    ]
