# Generated by Django 2.1.5 on 2022-10-18 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_by_feeling', '0029_auto_20221018_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allmusic',
            name='artist',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='アーティストタイトル'),
        ),
        migrations.AlterField(
            model_name='allmusic',
            name='popularity',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='人気度'),
        ),
    ]
