# Generated by Django 2.1.5 on 2022-10-23 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_by_feeling', '0032_auto_20221023_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoritemusiclist',
            name='order',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='通し番号'),
        ),
        migrations.AddField(
            model_name='music_by_feelinglist',
            name='order',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='通し番号'),
        ),
    ]
