# Generated by Django 2.1.5 on 2022-10-27 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_by_feeling', '0034_auto_20221025_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoritemusiclist',
            name='display_order',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='表示番号'),
        ),
        migrations.AddField(
            model_name='music_by_feelinglist',
            name='display_order',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='表示番号'),
        ),
    ]
