# Generated by Django 2.1.5 on 2022-11-14 14:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('music_by_feeling', '0037_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='Music_by_feeling_History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracks', models.CharField(max_length=50, null=True, verbose_name='トラックタイトル')),
                ('artist', models.CharField(max_length=50, null=True, verbose_name='アーティストタイトル')),
                ('danceability', models.FloatField(blank=True, default=0.0, null=True, verbose_name='踊りやすさ')),
                ('energy', models.FloatField(blank=True, default=0.0, null=True, verbose_name='エネルギッシュ')),
                ('key', models.FloatField(blank=True, default=0.0, null=True, verbose_name='曲の高さ')),
                ('loudness', models.FloatField(blank=True, default=0.0, null=True, verbose_name='音圧')),
                ('mode', models.FloatField(blank=True, default=0.0, null=True, verbose_name='スケール')),
                ('speechiness', models.FloatField(blank=True, default=0.0, null=True, verbose_name='話し言葉度')),
                ('acousticness', models.FloatField(blank=True, default=0.0, null=True, verbose_name='アコースティック感')),
                ('instrumentalness', models.FloatField(blank=True, default=0.0, null=True, verbose_name='ボーカル無し度')),
                ('liveness', models.FloatField(blank=True, default=0.0, null=True, verbose_name='ライブ感')),
                ('valence', models.FloatField(blank=True, default=0.0, null=True, verbose_name='ポジティブ')),
                ('tempo', models.FloatField(blank=True, default=0.0, null=True, verbose_name='テンポ')),
                ('type', models.CharField(max_length=50, null=True, verbose_name='タイプ')),
                ('url', models.CharField(max_length=100, null=True, verbose_name='URL')),
                ('track_id', models.CharField(max_length=100, null=True, verbose_name='track_id')),
                ('uri', models.CharField(max_length=100, null=True, verbose_name='URI')),
                ('track_href', models.CharField(max_length=100, null=True, verbose_name='曲の詳細情報にアクセスするAPIリンク')),
                ('analysis_url', models.CharField(max_length=100, null=True, verbose_name='曲のオーディオ分析にアクセスするAPIリンク')),
                ('duration_ms', models.FloatField(blank=True, default=0.0, null=True, verbose_name='曲の長さ')),
                ('time_signature', models.FloatField(blank=True, default=0.0, null=True, verbose_name='拍数')),
                ('artist_url', models.CharField(max_length=100, null=True, verbose_name='アーティストURL')),
                ('genres', models.CharField(max_length=100, null=True, verbose_name='ジャンル')),
                ('popularity', models.IntegerField(blank=True, default=0, null=True, verbose_name='人気度')),
                ('track_url', models.CharField(max_length=100, null=True, verbose_name='track_url')),
                ('created_year', models.IntegerField(blank=True, default=0, null=True, verbose_name='年')),
                ('rank', models.IntegerField(blank=True, default=0, null=True, verbose_name='順位')),
                ('order', models.IntegerField(blank=True, default=0, null=True, verbose_name='通し番号')),
                ('display_order', models.IntegerField(blank=True, default=0, null=True, verbose_name='表示番号')),
            ],
        ),
        migrations.CreateModel(
            name='Music_by_feeling_Selection_History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('danceability', models.FloatField(blank=True, default=0.0, null=True, verbose_name='踊りやすさ')),
                ('energy', models.FloatField(blank=True, default=0.0, null=True, verbose_name='エネルギッシュ')),
                ('artist', models.CharField(max_length=50, null=True, verbose_name='アーティスト名')),
                ('period', models.IntegerField(blank=True, default=0, null=True, verbose_name='年代')),
                ('genres', models.CharField(max_length=100, null=True, verbose_name='ジャンル')),
                ('popularity', models.BooleanField(blank=True, default=False, verbose_name='人気の曲から選ぶ')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='実施日')),
            ],
        ),
    ]
