# Generated by Django 2.1.5 on 2022-12-13 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_by_feeling', '0038_music_by_feeling_history_music_by_feeling_selection_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='date',
            field=models.DateTimeField(null=True, verbose_name='日付'),
        ),
        migrations.AlterField(
            model_name='music',
            name='artist',
            field=models.CharField(blank=True, default='5', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='music',
            name='era',
            field=models.CharField(blank=True, default='', max_length=5, null=True, verbose_name='年代'),
        ),
        migrations.AlterField(
            model_name='music',
            name='famous',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='music',
            name='genre',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
    ]
