# Generated by Django 2.1.5 on 2022-12-18 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_by_feeling', '0039_auto_20221213_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='allmusic',
            name='dance_down',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='踊りやすさダウン'),
        ),
        migrations.AddField(
            model_name='allmusic',
            name='dance_up',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='踊りやすさアップ'),
        ),
        migrations.AddField(
            model_name='allmusic',
            name='energy_down',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='エネルギッシュダウン'),
        ),
        migrations.AddField(
            model_name='allmusic',
            name='energy_up',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='エネルギッシュアップ'),
        ),
        migrations.AddField(
            model_name='favoritemusiclist',
            name='dance_down',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='踊りやすさダウン'),
        ),
        migrations.AddField(
            model_name='favoritemusiclist',
            name='dance_up',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='踊りやすさアップ'),
        ),
        migrations.AddField(
            model_name='favoritemusiclist',
            name='energy_down',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='エネルギッシュダウン'),
        ),
        migrations.AddField(
            model_name='favoritemusiclist',
            name='energy_up',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='エネルギッシュアップ'),
        ),
        migrations.AddField(
            model_name='music_by_feeling_history',
            name='dance_down',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='踊りやすさダウン'),
        ),
        migrations.AddField(
            model_name='music_by_feeling_history',
            name='dance_up',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='踊りやすさアップ'),
        ),
        migrations.AddField(
            model_name='music_by_feeling_history',
            name='energy_down',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='エネルギッシュダウン'),
        ),
        migrations.AddField(
            model_name='music_by_feeling_history',
            name='energy_up',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='エネルギッシュアップ'),
        ),
        migrations.AddField(
            model_name='music_by_feelinglist',
            name='dance_down',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='踊りやすさダウン'),
        ),
        migrations.AddField(
            model_name='music_by_feelinglist',
            name='dance_up',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='踊りやすさアップ'),
        ),
        migrations.AddField(
            model_name='music_by_feelinglist',
            name='energy_down',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='エネルギッシュダウン'),
        ),
        migrations.AddField(
            model_name='music_by_feelinglist',
            name='energy_up',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='エネルギッシュアップ'),
        ),
    ]
