# Generated by Django 2.1.5 on 2022-12-25 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_by_feeling', '0040_auto_20221218_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='allmusic',
            name='image_url',
            field=models.CharField(max_length=100, null=True, verbose_name='イメージURL'),
        ),
        migrations.AddField(
            model_name='favoritemusiclist',
            name='image_url',
            field=models.CharField(max_length=100, null=True, verbose_name='イメージURL'),
        ),
        migrations.AddField(
            model_name='music_by_feeling_history',
            name='image_url',
            field=models.CharField(max_length=100, null=True, verbose_name='イメージURL'),
        ),
        migrations.AddField(
            model_name='music_by_feelinglist',
            name='image_url',
            field=models.CharField(max_length=100, null=True, verbose_name='イメージURL'),
        ),
    ]
