# Generated by Django 2.2.28 on 2023-01-24 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_by_feeling', '0043_auto_20230125_0330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='era',
            field=models.CharField(blank=True, default='0', max_length=5, null=True, verbose_name='年代'),
        ),
    ]
