# Generated by Django 2.2.28 on 2023-01-25 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_by_feeling', '0045_allmusic_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allmusic',
            name='user',
        ),
    ]
