# Generated by Django 2.2.28 on 2023-01-25 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_by_feeling', '0046_remove_allmusic_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='music_by_feeling_selection_history',
            name='artist',
        ),
        migrations.AlterField(
            model_name='history',
            name='artist',
            field=models.CharField(max_length=50, null=True, verbose_name='アーティストタイトル'),
        ),
    ]
