# Generated by Django 2.1.5 on 2023-01-25 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_by_feeling', '0047_remove_music_by_feeling_selection_history_artist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='artist',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
